version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shoppingcart
    ports:
      - "5432:5432"

volumes:
  postgres_data: